{% set name = "pacini_typing" %}
{% set version = "3.0.1" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: https://github.com/RIVM-bioinformatics/Pacini-typing/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 28b17639e9291c71797d8e477e1e8b67776e49f7bbf6d94d02e60591cbc91a19

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv
  run_exports:
    - {{ pin_subpackage("pacini_typing", max_pin="x") }}

requirements:
  host:
    - python >=3.12
    - pip
    - setuptools
  run:
    - python >=3.12
    - biopython
    - setuptools
    - pysam
    - pyyaml
    - networkx
    - scipy
    - numpy
    - tqdm
    - pandas
    - blast
    - kma

test:
  commands:
    - pacini_typing --help
    - Pacini-typing --help

about:
  home: "https://github.com/RIVM-bioinformatics/Pacini-typing"
  license: AGPL-3.0
  license_file: LICENSE
  summary: "YAML-based bacterial genotyping application"
  dev_url: "https://github.com/RIVM-bioinformatics/Pacini-typing"

extra:
  recipe-maintainers:
    - MarkStreek
